"""empty message

Revision ID: 026dc30ff182
Revises: 8add424257c0
Create Date: 2026-01-18 13:18:45.273984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026dc30ff182'
down_revision: Union[str, Sequence[str], None] = '8add424257c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_inbox', sa.Column('test_col', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_inbox', 'test_col')
    # ### end Alembic commands ###
