"""removed test_col

Revision ID: 02de80f2cce2
Revises: 026dc30ff182
Create Date: 2026-01-18 13:20:39.982087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02de80f2cce2'
down_revision: Union[str, Sequence[str], None] = '026dc30ff182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_inbox', 'test_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_inbox', sa.Column('test_col', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
