"""rename of offset column

Revision ID: 5ed709adaa90
Revises: 02de80f2cce2
Create Date: 2026-01-18 18:25:03.415853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed709adaa90'
down_revision: Union[str, Sequence[str], None] = '02de80f2cce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_inbox", sa.Column("kafka_offset", sa.BigInteger(), nullable=True))
    op.execute('update event_inbox set kafka_offset = "offset"')
    op.alter_column("event_inbox", "kafka_offset", nullable=True)
    op.create_unique_constraint('uq_event_inbox_msg', 'event_inbox', ['topic', 'partition', 'kafka_offset'])
    op.drop_column('event_inbox', 'offset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_inbox', sa.Column('offset', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_event_inbox_msg', 'event_inbox', type_='unique')
    op.drop_column('event_inbox', 'kafka_offset')
    # ### end Alembic commands ###
