"""minio pointers

Revision ID: c94c48c7e79d
Revises: fe3b2c39ffb1
Create Date: 2026-01-20 19:15:20.165245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94c48c7e79d'
down_revision: Union[str, Sequence[str], None] = 'fe3b2c39ffb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_inbox', sa.Column('payload_s3_key', sa.Text(), nullable=True))
    op.add_column('event_inbox', sa.Column('payload_size_bytes', sa.Integer(), nullable=True))
    op.add_column('event_inbox', sa.Column('payload_content_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_inbox', 'payload_content_type')
    op.drop_column('event_inbox', 'payload_size_bytes')
    op.drop_column('event_inbox', 'payload_s3_key')
    # ### end Alembic commands ###
