"""empty message

Revision ID: fd8a466311b3
Revises: 5ed709adaa90
Create Date: 2026-01-18 18:38:20.035172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8a466311b3'
down_revision: Union[str, Sequence[str], None] = '5ed709adaa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_inbox', 'kafka_offset',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_inbox', 'kafka_offset',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
