"""last_error column

Revision ID: fe3b2c39ffb1
Revises: fd8a466311b3
Create Date: 2026-01-19 13:05:57.255753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3b2c39ffb1'
down_revision: Union[str, Sequence[str], None] = 'fd8a466311b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_inbox', sa.Column('attempts', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('event_inbox', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_inbox', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_inbox', 'last_error')
    op.drop_column('event_inbox', 'next_retry_at')
    op.drop_column('event_inbox', 'attempts')
    # ### end Alembic commands ###
